### PR TITLE
Allow a callback prop to be passed in and used onAnimationEnd. Update…

### PR DESCRIPTION
**Pull request by lucasdellabella**
… README.md accordingly.

### CODE REVIEW

**Comment by chenjiahan** [comment]
Thanks for you PR! this feature has been released in version 1.5.2.

**Comment by lucasdellabella** [comment]
Ah perfect, thanks! :)

**Comment by lucasdellabella** [comment]
In retrospect maybe there should be separate callbacks on onAnimationInEnd and onAnimationOutEnd... 不好意思，我可能明天修一下 😊 forgive me

**Comment by chenjiahan** [comment]
haha, no problem!

**Pull request merged**
